language: android
jdk: oraclejdk8
sudo: required

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.3

    # The SDK version used to compile your project
    - android-25

before_install:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

script:
  - ./gradlew build
  - ./gradlew test

notifications:
    slack: sdsmdg:hBRszERiXBQVCRKHljR1Ilwk
